name: build-and-test

on:
  push:
    paths-ignore:
      - '*.md'
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - run: ./build-and-test
